export const data = {
  userData: [
    {
      id: 1,
      specificDesignation : "Face Pimple Problem",
      doctorName : "Dr. Stanford M",
      Designation : "dentist",
      price : '$345',
      expireInDays  : "14 days",
    }, {
        id: 2,
        specificDesignation : "Face Pimple Problem",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
    {
        id: 3,
        specificDesignation : "Hypertention",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 4,
        specificDesignation : "Face Pimple Problem",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 5,
        specificDesignation : "Face Pimple Problem",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 6,
        specificDesignation : "Face Pimple Problem",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 7,
        specificDesignation : "Last",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 8,
        specificDesignation : "Last",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 9,
        specificDesignation : "Last",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 10,
        specificDesignation : "Last",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 11,
        specificDesignation : "Last",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 12,
        specificDesignation : "Last",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 13,
        specificDesignation : "Last",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 14,
        specificDesignation : "Last",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 15,
        specificDesignation : "Last",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 16,
        specificDesignation : "Last",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 17,
        specificDesignation : "Last",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 18,
        specificDesignation : "Last",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 19,
        specificDesignation : "Last",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 20,
        specificDesignation : "Last",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 21,
        specificDesignation : "Last",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 22,
        specificDesignation : "Last",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 23,
        specificDesignation : "Last",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },
      {
        id: 24,
        specificDesignation : "Last",
        doctorName : "Dr. Stanford M",
        Designation : "dentist",
        price : '$345',
        expireInDays : "14 days",
      },


  ],
};
